# In this configuration, the package is tested against multiple versions of python
# on Linux and on one version of Python on Windows. If and only if all tests pass
# will the wheels be built and deployed. Further, deployment is only initiated if
# the current branch is "master", the current commit is tagged, and the current
# repo is yours (e.g. it won't run on a Pull Request). For convenience, a source
# distribution is also created.

env:
  - global:
      - TWINE_USERNAME=__token__
      # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" = windows ]]; then
        choco install anaconda3 --params /AddToPath
        dir C:\tools\anaconda3\bin
        doskey python3=C:\tools\anaconda3\bin\python3
    fi
    if [[ "$TRAVIS_OS_NAME" = osx ]]; then
        alias python3="/usr/local/opt/python@3.8/bin/python3"
        alias pip3="/usr/local/opt/python@3.8/bin/pip3"
    fi

install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -r test-requirements.txt
  - python3 -m pip install -v .

script:
  - pytest

jobs:
  include:
    # Optional: run a test on Windows
    - os: linux
      dist: bionic
      language: python
      python:
        - 3.6
      addons:
        apt:
          packages:
            - libgfortran5
    - os: linux
      dist: bionic
      language: python
      python:
        - 3.7
      addons:
        apt:
          packages:
            - libgfortran5
    - os: linux
      dist: bionic
      language: python
      python:
        - 3.8
      addons:
        apt:
          packages:
            - libgfortran5
    - os: osx
      language: shell
      addons:
        homebrew:
          update: true
          packages:
            - python@3.8
          casks:
            - gfortran
      before_cache:
        - brew cleanup
    - os: windows
      language: shell

deploy:
  provider: pypi
  skip_existing: true
  user: AWehrhahn
  password:
    secure: YCJyHTiRXTIo0oB+vukZUIpdeUyGXOvUGVMcfxE8dcRq0FSWwPD55mj18LI7iZCAYnUocFeZGmC/zMyn0aUBVLAanucUUKKLvcy3zmiKrYUs5JSjPUp3m0AgXYxG2zVPfx1yZyjCdlHYx9BMHxzzMUE1cpiY3DFYu3Q5C9XhDtR+dzjs0vvjSyVq8WDKTrecNglnxzhusGASSsagtH1t5IWbg7DW9/k853hxRHTmczTN6Y5SviBS9ujgYtRmfNluTub4y15pNVIgwnOgthcJ1mW0p4zSKAsNNYDShTap1n6Cu5iaTP4TRrt+IOi6juqqlhnRGnZdPjBnjdfn6RQk422RueAkz2pBMTb20nidALnM1/xinuSe5NYuURUxCt1mkWoqViK0qsTB4Ph/TTdOEQ8e8qFvmqlqeLGm9ahBDPuhJyIdq5E5OAVOm0Xock4kL7UZmaq+PccT5/j0hsKg09f9mXR9lX80JWit+FJ1KjpHNcmfg68TPc6+tasinrjHt2Peid7VlnN8tbjb8XDGOWD0eLxKacXXmdgT+ql1nKL8TXBDbSszxj9Al0zNNwxzhlaimMR/xWsCuWw5ouLqiFOLHO31l8HH3tKWQX/z4urKUlVXayijje9hpXRO4RWFiHi6/CtrxPZZJeOhyopgBotf4KSliDspblLPe0F0KyE=
  on:
    tags: true
