env: 
  global:
    - TWINE_USERNAME=AWehrhahn
    - TWINE_PASSWORD=YCJyHTiRXTIo0oB+vukZUIpdeUyGXOvUGVMcfxE8dcRq0FSWwPD55mj18LI7iZCAYnUocFeZGmC/zMyn0aUBVLAanucUUKKLvcy3zmiKrYUs5JSjPUp3m0AgXYxG2zVPfx1yZyjCdlHYx9BMHxzzMUE1cpiY3DFYu3Q5C9XhDtR+dzjs0vvjSyVq8WDKTrecNglnxzhusGASSsagtH1t5IWbg7DW9/k853hxRHTmczTN6Y5SviBS9ujgYtRmfNluTub4y15pNVIgwnOgthcJ1mW0p4zSKAsNNYDShTap1n6Cu5iaTP4TRrt+IOi6juqqlhnRGnZdPjBnjdfn6RQk422RueAkz2pBMTb20nidALnM1/xinuSe5NYuURUxCt1mkWoqViK0qsTB4Ph/TTdOEQ8e8qFvmqlqeLGm9ahBDPuhJyIdq5E5OAVOm0Xock4kL7UZmaq+PccT5/j0hsKg09f9mXR9lX80JWit+FJ1KjpHNcmfg68TPc6+tasinrjHt2Peid7VlnN8tbjb8XDGOWD0eLxKacXXmdgT+ql1nKL8TXBDbSszxj9Al0zNNwxzhlaimMR/xWsCuWw5ouLqiFOLHO31l8HH3tKWQX/z4urKUlVXayijje9hpXRO4RWFiHi6/CtrxPZZJeOhyopgBotf4KSliDspblLPe0F0KyE=

jobs:
  - name: linux-test
    dist: bionic
    language: gcc
    env:
      - $OUTPUT_DIRS="lib share"
    addons:
      apt:
        packages:
        - g++
        - libgfortran3
        - gfortran
        - make
        - python3.8
        - python3-venv
        - python3-pip
    deploy: skip 
  - name: manylinux2010
    service: docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
    install:
      - docker pull $DOCKER_IMAGE
      - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
    script:
      - ls wheelhouse
    deploy:
      provider: script
      script: bash travis/deploy.sh
      on:
        tags: true      
  - name: osx
    os: osx
    language: gcc
    env:
      - TARGET=osx
      - FORTRAN_DIR="/usr/local/gfortran/lib/"
      - LDFLAGS="-L$FORTRAN_DIR"
      - OUTPUT_DIRS="lib share"
    addons:
      homebrew:
        update: true
        packages:
        - python@3.8
        - gcc
        - make
        - automake
        - autoconf
        - libtool
        - ccache
        casks:
        - gfortran
    before_cache:
      - brew cleanup
    cache:
      - pip
      - ccache
      - directories:
        - $HOME/Library/Caches/Homebrew
    before_install:
      - alias python3="/usr/local/opt/python@3.8/bin/python3"
      - alias pip3="/usr/local/opt/python@3.8/bin/pip3"
      - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - name: win32
    os: linux
    dist: bionic
    language: gcc
    env:
      - TARGET=win64
      - FORTRAN_DIR="$(x86_64-w64-mingw32-gfortran --print-file-name=)"
      - LDFLAGS="-L$FORTRAN_DIR"
      - CXX=x86_64-w64-mingw32-gcc
      - F77=x86_64-w64-mingw32-gfortran
      - CONFIG_FLAGS="--build=x86_64-pc-linux-gnu --host=x86_64-w64-mingw32"
      - OUTPUT_DIRS="bin share"
    addons:
      apt:
        packages:
        - g++
        - gfortran
        - make
        - libtool
        - mingw-w64
        - mingw-w64-tools
        - mingw-w64-common
        - gfortran-mingw-w64
        - gfortran-mingw-w64-x86-64
        - gcc-mingw-w64
        - gcc-mingw-w64-x86-64
        - g++-mingw-w64
        - g++-mingw-w64-x86-64
    # Skip testing for Windows target
    script:
      - ls src/pysme
      - ls src/pysme/bin
      - ls src/pysme/share/libsme

install:
  - cd smelib
  - ./bootstrap
  - ./configure --prefix=$PWD $CONFIG_FLAGS
  - make install
  - cp -R $OUTPUT_DIRS ../src/pysme/
  - cd ..
  - pip3 install setuptools
  - pip3 install pytest
  - pip3 install -r requirements.txt

script:
  - python3 -m pytest test/

deploy:
  provider: pypi
  user: AWehrhahn
  password:
    secure: YCJyHTiRXTIo0oB+vukZUIpdeUyGXOvUGVMcfxE8dcRq0FSWwPD55mj18LI7iZCAYnUocFeZGmC/zMyn0aUBVLAanucUUKKLvcy3zmiKrYUs5JSjPUp3m0AgXYxG2zVPfx1yZyjCdlHYx9BMHxzzMUE1cpiY3DFYu3Q5C9XhDtR+dzjs0vvjSyVq8WDKTrecNglnxzhusGASSsagtH1t5IWbg7DW9/k853hxRHTmczTN6Y5SviBS9ujgYtRmfNluTub4y15pNVIgwnOgthcJ1mW0p4zSKAsNNYDShTap1n6Cu5iaTP4TRrt+IOi6juqqlhnRGnZdPjBnjdfn6RQk422RueAkz2pBMTb20nidALnM1/xinuSe5NYuURUxCt1mkWoqViK0qsTB4Ph/TTdOEQ8e8qFvmqlqeLGm9ahBDPuhJyIdq5E5OAVOm0Xock4kL7UZmaq+PccT5/j0hsKg09f9mXR9lX80JWit+FJ1KjpHNcmfg68TPc6+tasinrjHt2Peid7VlnN8tbjb8XDGOWD0eLxKacXXmdgT+ql1nKL8TXBDbSszxj9Al0zNNwxzhlaimMR/xWsCuWw5ouLqiFOLHO31l8HH3tKWQX/z4urKUlVXayijje9hpXRO4RWFiHi6/CtrxPZZJeOhyopgBotf4KSliDspblLPe0F0KyE=
  on:
    tags: true
