jobs:
  include:
  - os: linux
    dist: bionic
    language: python
    python: 3.8
    addons:
      apt:
        packages:
        - libgfortran5
  - os: linux
    dist: xenial
    language: python
    python: 3.6
    addons:
      apt:
        packages:
        - libgfortran3
  - os: osx
    language: shell
    addons:
      homebrew:
        update: true
        packages:
        - python@3.8
        casks:
        - gfortran
    before_cache:
    - brew cleanup
    cache:
      directories:
      - "$HOME/Library/Caches/Homebrew"
    before_install:
    - alias python3="/usr/local/opt/python@3.8/bin/python3"
    - alias pip3="/usr/local/opt/python@3.8/bin/pip3"
install:
- python3 -m pip install -r requirements.txt
- python3 -m pip install -r test-requirements.txt
- python3 -m pip install -v .

script:
- python3 -m pytest

deploy:
  provider: pypi
  skip_existing: true
  user: AWehrhahn
  password:
    secure: YOys0c55Vv5YVMajms2M/exuONwjiF+ilkAGK4/AkdiUZoPFGIHhfBT8etFhfaxvVyYkaya9HklhculrNhqMRgUTYW1CDtpLevWgcP4z18tbX5d+qnhIxlyJqBDoSODqbpyBwpU7pzg8fe2Up0VdXSOMlAjCzcSctQc4QJ1pdUxnD3jhomecE2hd2Cqp4SVXciqtth3FdWEm9H/DalYJwCPgb9Zg8tGcWhqG/doim5W3zJZLXnlkQybYEJjMI/ij2fFmjuqUWC7BI+20e71HPcjseJgoWxBSxyJztYod3k386reizf6aHlyi+C8IZo1KVDSRbXKVe7hKcNg+q8q/9YT5rPZ/QajPMpQbXYx5KNAhQqnkE9Z7KPqMhLZgDaCE7dML4nePL7C1/o2Si8HHuHKpQOaEtGoxHOobs/v9xqtisoDY0gmgnrtvgrlHXZuOUYOscER9qC8nYZwG5OVbwh8v11PEBohkNeywH+IoMleb6ChUjEtVRKLxWp5NoBH0kmj827/DhaQiE6sV224p3F183ZUMvWsvGqrJmA7PzonQ5hSZMR4oAVkfeL9+/518qJziARPki0qAvhTBDVTBhzaUNlehRDvFknz6pNVdflXKHqk5DpDVaP84ERQCzGIE3xGZpNx8X60h3KJlEiqImiqDqI6kEsAz9nEvoGlNNqo=
  on:
    tags: true
    repo: AWehrhahn/SME
  skip_cleanup: 'true'
